Check format after npm docs check

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -34,10 +34,6 @@ for directory in "${directories[@]}"; do
             echo "Type checking failed. Please fix the issues before committing."
             exit 1
         fi
-        if ! npm run format:check --if-present --prefix $root_path/$directory; then
-            echo "Formatting check failed. Please fix the issues before committing."
-            exit 1
-        fi
         
         # Check for changes in front/pages/api/v1/ only when processing the front/ directory
         if [ "$directory" = "front" ]; then
@@ -47,6 +43,11 @@ for directory in "${directories[@]}"; do
                     exit 1
                 fi
             fi
+        fi
+
+        if ! npm run format:check --if-present --prefix $root_path/$directory; then
+            echo "Formatting check failed. Please fix the issues before committing."
+            exit 1
         fi
     fi
 done
