dev(lint): add eslint to lint-staged, faster faster

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -37,8 +37,8 @@ directories=("front" "connectors")
 for directory in "${directories[@]}"; do
     if git diff --cached --name-only | grep -qE "^$directory/"; then
         # Run the linter on root_path concatenated with the directory
-        if ! npm run lint --if-present --prefix $root_path/$directory; then
-            echo "Linting failed. Please fix the issues before committing."
+        if ! npm run lint:test-filenames --if-present --prefix $root_path/$directory; then
+            echo "Linting test-filenames failed. Please fix the issues before committing."
             exit 1
         fi
         if ! npm run tsc --if-present --prefix $root_path/$directory; then
