[.github] - feature: enforce main branch deployments for specific components (#11352)
- Add a check-branch job in the deploy workflow to ensure only the main branch can deploy certain components
 - Block deployments of inputs.component if they are not from the main branch, except for 'front-edge' and 'front-qa'

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,7 +43,17 @@ concurrency:
   cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
 
 jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if deployment is from main branch
+        if: ${{ github.ref != 'refs/heads/main' && inputs.component != 'front-edge' && inputs.component != 'front-qa' }}
+        run: |
+          echo "Error: Deployments for ${{ inputs.component }} are only allowed from the main branch"
+          exit 1
+
   prepare:
+    needs: [ check-branch ]
     runs-on: ubuntu-latest
     outputs:
       short_sha: ${{ steps.short_sha.outputs.short_sha }}
